### ISSUE TITLE
Alfred 3 Montery support 

### ISSUE THREAD

**Issue by MBischof-gcx** [dennis-tra/alfred-dict.cc-workflow#9]
Hi there,
as mentioned in the release notes the Montery update with the switch to GO does not support Alfred 3 anymore. Can anybody point me into a direction how to change that? I would also get my hands dirty and change some things to make it work, I just don't know where to start. I can't find anything in the Info.plist that looks like an exclusive Alfred 4 thing.

Currently I don't really see a reason to upgrade from Alfred 3 to 4 since I am still super happy with it and it does everything I need it to (apart from working with this Workflow 😅)

Thanks for your help in advance!

**Comment by dennis-tra** [comment]
Hi @MBischof-gcx,

that's right, there is nothing that would prohibit this workflow from running in Alfred 3. However, I guess the only way is to recreate the workflow in Alfred 3 as I don't know what has changed in the `info.plist` format. That's not a difficult task, though, because most of the logic resides inside the binaries.

Just create a blank workflow with the following components and configurations:

![image](https://user-images.githubusercontent.com/11836793/165040678-32f70e08-ae8d-4af1-a38e-f939242d1437.png)
Script Filter:

![image](https://user-images.githubusercontent.com/11836793/165040492-99fba989-d772-4c00-b386-b9b7cbf91c30.png)

Post Notification:

![image](https://user-images.githubusercontent.com/11836793/165040984-56b983dc-b1c8-46f9-b645-1843fb2daead.png)

In the end, copy the binaries into the workflow directory.

Let me know if you get stuck at any of these steps 👍

**Comment by MBischof-gcx** [comment]
It worked! Thank you so much
[Dictcc_Alfred3_Montery.alfredworkflow.zip](https://github.com/dennis-tra/alfred-dict.cc-workflow/files/8552753/Dictcc_Alfred3_Montery.alfredworkflow.zip)
!

**Comment by MBischof-gcx** [comment]
Bought you a coffee 😁 Keep up the awesome work!

**Comment by dennis-tra** [comment]
Awesome :) That's so nice! Thanks a ton :)
